### ISSUE TITLE
Day 2 Deliverables

### ISSUE THREAD

**Issue by JamieCaudill** [SethBurns/rancid-tomatillos#2]
- [x] Link to 2-3 pieces of design inspiration
- [x] Wireframe of app
- [x] Initial plan for component architecture

**Comment by JamieCaudill** [comment]
https://www.imdb.com/
https://www.plex.tv/
https://www.rottentomatoes.com/
https://www.netflix.com/browse

**Comment by SethBurns** [comment]
![Image](https://github.com/SethBurns/rancid-tomatillos/assets/123792434/4c887f56-812c-4f3b-97bc-0315fa6a8872)

**Comment by JamieCaudill** [comment]
- What components do you envision needing?
    - Movies component
    - Poster component
    - MovieDetails component
    - Home component
- Where will data be stored?
    - In the movies state in App.js
- How will information be passed around?
    - using props
