### ISSUE TITLE
As a user, all movies should be displayed on the homepage.

### ISSUE THREAD

**Issue by JamieCaudill** [SethBurns/rancid-tomatillos#6]
### Summary

As a user, when I visit the app, all movies should be displayed so I can interact with them (get details, add to a list, etc).

### Acceptance Criteria

1. When I access the site
1. All movies should be displayed

Also, here are a few points that need to be addressed:

1. If an error occurs
1. I will see an informational error message

**Comment by SethBurns** [comment]
![DisplayAllMovies](https://github.com/SethBurns/rancid-tomatillos/assets/123792434/0ebaf522-dbc7-4c09-94f5-46fe925bbcc9)
